### ISSUE TITLE
Error after running python first_setup.py on local machine

### ISSUE THREAD

**Issue by oldPadavan** [numbas/editor#425]
I get an error trying to install editor on my local machine. After activating virtualenv and installing requirements I run `python first_setup.py` but it raised an exception:
```
python first_setup.py
This script will configure the Numbas editor up to a point where you can open it in a web browser, based on your answers to the following questions.

Traceback (most recent call last):
  File "first_setup.py", line 273, in <module>
    command.handle()
  File "first_setup.py", line 72, in handle
    self.get_values()
  File "first_setup.py", line 111, in get_values
    self.get_value(question)
  File "first_setup.py", line 140, in get_value
    self.values[question.key] = self.get_input(question.question, default, question.validation)
UnboundLocalError: local variable 'default' referenced before assignment
```

**Comment by christianp** [comment]
Whoops, not sure how I managed not to test that. I've fixed this - please do a `git pull` and let me know how you get on.
